autoDeploy: false

kubearmorOperator:
  name: kubearmor-operator
  image:
    repository: kubearmor/kubearmor-operator
    tag: ""
  imagePullPolicy: IfNotPresent

kubearmorConfig:
  defaultCapabilitiesPosture: audit
  defaultFilePosture: audit
  defaultNetworkPosture: audit
  defaultVisibility: process,network
  enableStdOutLogs: false
  enableStdOutAlerts: false
  enableStdOutMsgs: false
  seccompEnabled: true

# DO NOT CHANGE THIS VALUES 
# changing these values will require code changes with the operator
# these secret names should match with the secrets managed by the operator
tlsSecrets:
  kubearmorCa: kubearmor-ca
  kubearmorClient: kubearmor-client-certs
  relayServer: kubearmor-relay-server-certs
  controllerWebhook: kubearmor-controller-webhook-server-cert